apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudapp
  labels:
    app: cloudapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudapp
  template:
    metadata:
      labels:
        app: cloudapp
    spec:
      containers:
      - image: rg3398/cloudapp
        name: cloudapp
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}