apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudapp
  labels:
    app: cloudapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudapp
  template:
    metadata:
      labels:
        app: cloudapp
    spec:
      containers:
      - name: cloudapp
        image: rg3398/cloudapp
        ports:
          - containerPort: 5000
        imagePullPolicy: Always