apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudapp
  labels:
    app: cloudapp

spec:
  replicas: 1
  strategy:
  type: RollingUpdate
    maxUnavailable: 2
  selector:
    matchLabels:
      app: cloudapp
  template:
    metadata:
      labels:
        app: cloudapp
    spec:
      containers:
      - name: cloudapp
        image: rg3398/cloudapp
        ports:
          - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        imagePullPolicy: Always