services:
  web:
    image: cloudapp
    ports: 
      - "8000:5000"
    environment:
      MONGODB_USERNAME: "root"
      MONGODB_PASSWORD: "CS6998"
    depends_on:
      - db
  
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=CS6998
    ports:
      - "27017:27017"
    volumes:
      - myvolume:/data/db

volumes:
  myvolume: