services:
  web:
    image: cloudapp
    ports: 
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
  
  db:
    image: mongo
    hostname: test_mongodb
    environment:
      - MONGO_INIT_DB_DATABSE=camp2016
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=CS6998
    ports:
      - "27017:27017"
    volumes:
      - myvolume:/data/db

volumes:
  myvolume: