apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INIT_DB_DATABSE
            value: 'camp2016'
          - name: MONGO_INITDB_ROOT_USERNAME
            value: 'root'
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: 'CS6998'
        volumeMounts:
          - name: "mongo-data-dir"
            mountPath: "/data/mongo"
      volumes:
        - name: "mongo-data-dir"
          persistentVolumeClaim:
            claimName: "mongodb"
