apiVersion: v1
kind: Service
metadata:
  name: part4-service
  namespace: eks-hw3-app
  labels:
    app: eks-part4-app
spec:
  selector:
    app: eks-part4-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000